#!/bin/sh
if [ $# -eq 0 ]; then
  echo $0 HOST:PORT ...
  exit 2
fi
hostport=$1
host=${hostport%:*}
port=${hostport#*:}
if ping -W1 -c1 $host >/dev/null 2>/dev/null ; then
  nc $host $port
  exit 0
fi
shift
if [ $# -eq 0 ]; then
  echo could not connect
  exit 1
fi
exec $0 "$@"
